[build]
  publish = "build/web"
  command = "pip install -r requirements.txt && python -m flet build main_pyodide.py --output build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
