[build]
command = "python -m venv venv && . venv/bin/activate && pip install flet && ls -la && flet publish main.py"
publish = "build/web"

[redirects]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache"